network:
  interface: "eth1"
  cycle_time_us: 1000
  timeout_ms: 1000

performance:
  rt_priority: 99
  cpu_affinity: [2, 3]
  buffer_size: 8192

logging:
  level: "info"
  file: "/var/log/etherforged.log"
  max_size: "100MB"

security:
  bind_address: "0.0.0.0"
  port: 2346
  max_clients: 32